source 'https://rubygems.org'
ruby '2.3.0'

gem 'rails', '4.2.1'
gem 'pg'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'haml-rails'
gem 'pry'
gem 'devise'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'sass-rails', '~> 5.0'
gem 'knack-rails'
gem 'font-awesome-rails'
gem 'elementaljs-rails'
gem 'friendly_id'
gem 'paperclip'
gem 'aws-sdk', '~> 2'
gem 'remotipart'
gem 'nested_form'
gem 'aws-s3', require: false
gem 'autoprefixer-rails'
gem 'papercrop', '~> 0.3.0'
gem 'socialization'
gem 'wiselinks'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'dotenv-rails'
end

