default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: admin
  password: password

development:
  <<: *default
  database: ournet_development

test:
  <<: *default
  database: ournet_test

production:
  <<: *default
  database: mighty-citadel-46136_production
  username: mighty-citadel-46136
  password: <%= ENV['OURNET_DATABASE_PASSWORD'] %>
