default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: admin
  password: password

development:
  <<: *default
  database: ournet_development

test:
  <<: *default
  database: ournet_test

production:
  <<: *default
  database: ukraine_custom_culture_production
  username: ukraine_custom_culture
  password: <%= ENV['OURNET_DATABASE_PASSWORD'] %>
